# The URL the site will be built for
base_url = "https://akmijares.pages.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The site theme to use.
theme = "blow"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

enable_search = true
enable_sidebar = false
enable_adsense = false
enable_multilingue = false

[extra.navbar]
items = [
    { lang = "en", links = [
        { url = "/", name = "Home" },
        { url = "/about-me", name = "About" },
        { url = "/resume", name = "Resume" },
        { url = "/projects", name = "Projects" },
        { url = "/blog", name = "Blog" }
    ] },
]
title = "akmijares"

# Index page
[extra.index]
title = "Antonio Karlo Mijares"
image = "img/home-page.jpg"
image_alt = "Picture of Antonio Karlo Mijares"

[extra.default_author]
name = "Antonio Karlo Mijares"
avatar = "https://akmijares.ca/assets/img/home-page.jpg"
avatar_alt = "Picture of Antonio Karlo Mijares"

[extra.social]
github = "https://github.com/akmijares"
linkedin = "https://www.linkedin.com/in/akmijares/"
email = "antonio.karlo@akmijares.ca"

[extra.favicon]
favicon_16x16 = "favicon.ico"
